modLoader = "javafml"
loaderVersion = "[47,)"
issueTrackerURL = "https://github.com/celsiusqc/totw_modded_mod/blob/1.20.1/build.gradle"
license = "Insert License Here"

[[mods]]
modId = "totw_modded"
version = "${version}"
displayName = "Towers Of The Wild: Modded"
authors = "Me!"
description = '''
This is an example description! Tell everyone what your mod is about!
'''
#logoFile = ""

[[dependencies.totw_modded]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.totw_modded]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.totw_modded]]
modId = "architectury"
mandatory = true
versionRange = "[9.1.12,)"
ordering = "AFTER"
side = "BOTH"